[package]
name = "sable-resolve"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]
