use cbindgen::{
  EnumConfig,
  RenameRule,
};

fn main() {
  let path = std::env::var("CARGO_MANIFEST_DIR").unwrap();

  let cfg = cbindgen::Config {
    enumeration: EnumConfig {
      rename_variants: RenameRule::ScreamingSnakeCase, //there is also qualified version choose your poison but with qualified the names can get pretty long
      ..Default::default()
    },
    include_guard: Some("SABLE_FFI_H".to_string()),
    language: cbindgen::Language::C,
    package_version: true,
    autogen_warning: Some(
      "//This file is automatically generated by cbindgen. Do not edit this file manually."
        .to_string(),
    ),
    usize_is_size_t: true,
    ..Default::default()
  };

  cbindgen::Builder::new()
    .with_crate(path)
    .with_config(cfg)
    .generate()
    .expect("Unable to generate bindings")
    .write_to_file("sable-ffi.h");
}
