/* Package version: 0.1.0 */

#ifndef SABLE_FFI_H
#define SABLE_FFI_H

//This file is automatically generated by cbindgen. Do not edit this file manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* SABLE_FFI_H */
