[package]
name = "sable-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = { workspace = true }
sable-common = { workspace = true }
sable-ast = { workspace = true }
smallvec = { workspace = true }
either = { workspace = true }
lsp-types = { workspace = true }