[package]
name = "sable-lowering"
version = "0.1.0"
edition = "2024"

[dependencies]
sable-common = { workspace = true }
sable-ast = { workspace = true }
sable-hir = { workspace = true }
sable-arena = { workspace = true }

either = { workspace = true }
smallvec = { workspace = true }