[package]
name = "sable-middle"
version = "0.1.0"
edition = "2024"

[dependencies]
sable-common = { workspace = true }
sable-arena = { workspace = true }

indexmap = { workspace = true }
getset = { workspace = true }