[package]
name = "sable-hir"
version = "0.1.0"
edition = "2024"

[dependencies]
sable-ast = { workspace = true }
sable-arena = { workspace = true }
sable-common = { workspace = true }

getset = { workspace = true }
typed-builder = { workspace = true }
indexmap = { workspace = true }