#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_func = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_COLON = 4,
  anon_sym_COMMA = 5,
  anon_sym_STAR = 6,
  anon_sym_SEMI = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_var = 10,
  anon_sym_EQ = 11,
  anon_sym_PLUS = 12,
  anon_sym_DASH = 13,
  anon_sym_SLASH = 14,
  sym_integer_literal = 15,
  sym_float_literal = 16,
  sym_identifier = 17,
  sym_comment = 18,
  sym_source_file = 19,
  sym_function_declaration = 20,
  sym_parameter_list = 21,
  sym_parameter = 22,
  sym_type = 23,
  sym_pointer_suffix = 24,
  sym_block_or_semi = 25,
  sym_block = 26,
  sym_statement = 27,
  sym_variable_declaration = 28,
  sym_expression_statement = 29,
  sym_expression = 30,
  sym_assignment = 31,
  sym_additive = 32,
  sym_multiplicative = 33,
  sym_primary = 34,
  sym_literal = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_parameter_list_repeat1 = 37,
  aux_sym_pointer_suffix_repeat1 = 38,
  aux_sym_block_repeat1 = 39,
  aux_sym_additive_repeat1 = 40,
  aux_sym_multiplicative_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_STAR] = "*",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [sym_integer_literal] = "integer_literal",
  [sym_float_literal] = "float_literal",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_pointer_suffix] = "pointer_suffix",
  [sym_block_or_semi] = "block_or_semi",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_assignment] = "assignment",
  [sym_additive] = "additive",
  [sym_multiplicative] = "multiplicative",
  [sym_primary] = "primary",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_pointer_suffix_repeat1] = "pointer_suffix_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_additive_repeat1] = "additive_repeat1",
  [aux_sym_multiplicative_repeat1] = "multiplicative_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_integer_literal] = sym_integer_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_pointer_suffix] = sym_pointer_suffix,
  [sym_block_or_semi] = sym_block_or_semi,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_assignment] = sym_assignment,
  [sym_additive] = sym_additive,
  [sym_multiplicative] = sym_multiplicative,
  [sym_primary] = sym_primary,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_pointer_suffix_repeat1] = aux_sym_pointer_suffix_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_additive_repeat1] = aux_sym_additive_repeat1,
  [aux_sym_multiplicative_repeat1] = aux_sym_multiplicative_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_pointer_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_block_or_semi] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_additive] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicative] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pointer_suffix_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_additive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiplicative_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'v') ADVANCE(6);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'v') ADVANCE(30);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(64),
    [sym_function_declaration] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_func] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(12), 1,
      anon_sym_RBRACE,
    ACTIONS(14), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      sym_integer_literal,
    ACTIONS(20), 1,
      sym_float_literal,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(58), 1,
      sym_expression,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 2,
      sym_variable_declaration,
      sym_expression_statement,
  [48] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    ACTIONS(30), 1,
      anon_sym_var,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(36), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(58), 1,
      sym_expression,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 2,
      sym_variable_declaration,
      sym_expression_statement,
  [96] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      anon_sym_var,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(58), 1,
      sym_expression,
    STATE(3), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 2,
      sym_variable_declaration,
      sym_expression_statement,
  [144] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(66), 1,
      sym_expression,
  [178] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(63), 1,
      sym_expression,
  [212] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(54), 1,
      sym_expression,
  [246] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(40), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(29), 1,
      sym_multiplicative,
    STATE(46), 1,
      sym_assignment,
    STATE(53), 1,
      sym_additive,
    STATE(57), 1,
      sym_expression,
  [280] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_STAR,
    STATE(16), 1,
      aux_sym_pointer_suffix_repeat1,
    STATE(27), 1,
      sym_pointer_suffix,
    ACTIONS(42), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [300] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_multiplicative_repeat1,
    ACTIONS(46), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [319] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_STAR,
    ACTIONS(58), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_multiplicative_repeat1,
    ACTIONS(54), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [338] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(13), 1,
      sym_primary,
    STATE(18), 1,
      sym_literal,
    STATE(32), 1,
      sym_multiplicative,
  [363] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_STAR,
    ACTIONS(58), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      aux_sym_multiplicative_repeat1,
    ACTIONS(62), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [382] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_EQ,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(64), 5,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [399] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_STAR,
    STATE(15), 1,
      aux_sym_pointer_suffix_repeat1,
    ACTIONS(70), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [416] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_STAR,
    STATE(15), 1,
      aux_sym_pointer_suffix_repeat1,
    ACTIONS(75), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [433] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_integer_literal,
    ACTIONS(34), 1,
      sym_float_literal,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(18), 1,
      sym_literal,
    STATE(21), 1,
      sym_primary,
  [455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(64), 5,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 3,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
    ACTIONS(81), 3,
      anon_sym_var,
      sym_integer_literal,
      sym_identifier,
  [483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 3,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
    ACTIONS(85), 3,
      anon_sym_var,
      sym_integer_literal,
      sym_identifier,
  [497] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_SLASH,
    ACTIONS(46), 5,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_SLASH,
    ACTIONS(89), 5,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
    ACTIONS(95), 3,
      anon_sym_var,
      sym_integer_literal,
      sym_identifier,
  [539] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(97), 5,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
    ACTIONS(103), 3,
      anon_sym_var,
      sym_integer_literal,
      sym_identifier,
  [567] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_additive_repeat1,
    ACTIONS(105), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
    ACTIONS(107), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [582] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [593] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_additive_repeat1,
    ACTIONS(112), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_additive_repeat1,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(116), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [623] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_func,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(33), 2,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
  [637] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block_or_semi,
    STATE(51), 1,
      sym_block,
  [653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
  [663] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      anon_sym_func,
    STATE(33), 2,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
  [677] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(36), 1,
      sym_parameter,
    STATE(67), 1,
      sym_parameter_list,
  [693] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_block_or_semi,
    STATE(51), 1,
      sym_block,
  [709] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym_parameter_list_repeat1,
  [722] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
  [735] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_parameter_list_repeat1,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      anon_sym_func,
  [756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      anon_sym_func,
  [764] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(31), 1,
      sym_type,
  [774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(48), 1,
      sym_type,
  [784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      anon_sym_func,
  [792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(50), 1,
      sym_parameter,
  [802] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_COLON,
    ACTIONS(154), 1,
      anon_sym_EQ,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [820] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(62), 1,
      sym_type,
  [830] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [838] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(35), 1,
      sym_type,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [856] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      anon_sym_func,
  [864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_func,
  [872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_COLON,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
  [902] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_SEMI,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_identifier,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_COLON,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_identifier,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_EQ,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_SEMI,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
  [958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_COLON,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_SEMI,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 178,
  [SMALL_STATE(7)] = 212,
  [SMALL_STATE(8)] = 246,
  [SMALL_STATE(9)] = 280,
  [SMALL_STATE(10)] = 300,
  [SMALL_STATE(11)] = 319,
  [SMALL_STATE(12)] = 338,
  [SMALL_STATE(13)] = 363,
  [SMALL_STATE(14)] = 382,
  [SMALL_STATE(15)] = 399,
  [SMALL_STATE(16)] = 416,
  [SMALL_STATE(17)] = 433,
  [SMALL_STATE(18)] = 455,
  [SMALL_STATE(19)] = 469,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 497,
  [SMALL_STATE(22)] = 511,
  [SMALL_STATE(23)] = 525,
  [SMALL_STATE(24)] = 539,
  [SMALL_STATE(25)] = 553,
  [SMALL_STATE(26)] = 567,
  [SMALL_STATE(27)] = 582,
  [SMALL_STATE(28)] = 593,
  [SMALL_STATE(29)] = 608,
  [SMALL_STATE(30)] = 623,
  [SMALL_STATE(31)] = 637,
  [SMALL_STATE(32)] = 653,
  [SMALL_STATE(33)] = 663,
  [SMALL_STATE(34)] = 677,
  [SMALL_STATE(35)] = 693,
  [SMALL_STATE(36)] = 709,
  [SMALL_STATE(37)] = 722,
  [SMALL_STATE(38)] = 735,
  [SMALL_STATE(39)] = 748,
  [SMALL_STATE(40)] = 756,
  [SMALL_STATE(41)] = 764,
  [SMALL_STATE(42)] = 774,
  [SMALL_STATE(43)] = 784,
  [SMALL_STATE(44)] = 792,
  [SMALL_STATE(45)] = 802,
  [SMALL_STATE(46)] = 812,
  [SMALL_STATE(47)] = 820,
  [SMALL_STATE(48)] = 830,
  [SMALL_STATE(49)] = 838,
  [SMALL_STATE(50)] = 848,
  [SMALL_STATE(51)] = 856,
  [SMALL_STATE(52)] = 864,
  [SMALL_STATE(53)] = 872,
  [SMALL_STATE(54)] = 880,
  [SMALL_STATE(55)] = 888,
  [SMALL_STATE(56)] = 895,
  [SMALL_STATE(57)] = 902,
  [SMALL_STATE(58)] = 909,
  [SMALL_STATE(59)] = 916,
  [SMALL_STATE(60)] = 923,
  [SMALL_STATE(61)] = 930,
  [SMALL_STATE(62)] = 937,
  [SMALL_STATE(63)] = 944,
  [SMALL_STATE(64)] = 951,
  [SMALL_STATE(65)] = 958,
  [SMALL_STATE(66)] = 965,
  [SMALL_STATE(67)] = 972,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [9] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(8),
  [12] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [14] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(61),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(24),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(24),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(14),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiplicative_repeat1, 2),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiplicative_repeat1, 2), SHIFT_REPEAT(17),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multiplicative_repeat1, 2), SHIFT_REPEAT(17),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicative, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicative, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pointer_suffix_repeat1, 2),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pointer_suffix_repeat1, 2), SHIFT_REPEAT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pointer_suffix, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multiplicative_repeat1, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_additive_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_additive_repeat1, 2), SHIFT_REPEAT(12),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_additive, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(59),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(44),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 8),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_or_semi, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [186] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_sable(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
